<template>
   <div>
      <a-row type="flex" justify="end" align="middle">
         <a-col>
            <a-form layout="inline" style="width: 550px">
               <a-form-item label="设备节点">
                  <a-tree-select
                     v-model="value"
                     style="width: 200px"
                     :replaceFields="replaceFields"
                     :dropdown-style="{ maxHeight: '400px', overflow: 'auto' }"
                     :tree-data="treeData"
                     placeholder="请选择设备组织节点"
                  ></a-tree-select>
               </a-form-item>
               <a-form-item label="设备">
                  <a-select v-model="eq" placeholder="请选择设备" style="width: 200px">
                     <a-select-option value="11">123</a-select-option>
                  </a-select>
               </a-form-item>
            </a-form>
         </a-col>
         <a-col>
            <a-space>
               <a-button type="primary" icon="search">查询</a-button>
               <a-button type="primary" icon="sync">重置</a-button>
            </a-space>
         </a-col>
      </a-row>
      <fault-diagnosis theme="" />
   </div>
</template>

<script>
import FaultDiagnosis from '../eqMonitoring/components/faultDiagnosis.vue'
export default {
   components: { FaultDiagnosis },
   data() {
      return {
         value: undefined,
         treeData: [
            {
               parentOrganizationName: null,
               organizationTypeName: '集团',
               leadersName: '测试0221,测试0222,测试0228,范诗豪,袁泽龙',
               location: null,
               children: [
                  {
                     parentOrganizationName: '浙江中智达科技有限公司',
                     organizationTypeName: '公司',
                     leadersName: '小马,小汪,cccc',
                     location: null,
                     children: [
                        {
                           parentOrganizationName: '中智达',
                           organizationTypeName: '工厂',
                           leadersName: null,
                           location: null,
                           children: [],
                           positions: null,
                           externalRelations: null,
                           parentId: '167954423925047296',
                           name: '销售',
                           code: null,
                           type: 3,
                           enableTenant: false,
                           isExternal: false,
                           countOfUser: 1,
                           countOfUserCascaded: 1,
                           sort: null,
                           remark: null,
                           sourceId: null,
                           id: '208891413461598208',
                        },
                        {
                           parentOrganizationName: '中智达',
                           organizationTypeName: '工厂',
                           leadersName: null,
                           location: null,
                           children: [
                              {
                                 parentOrganizationName: '技术',
                                 organizationTypeName: '部门',
                                 leadersName: null,
                                 location: null,
                                 children: [],
                                 positions: null,
                                 externalRelations: null,
                                 parentId: '164306583474536448',
                                 name: '研发中心',
                                 code: null,
                                 type: 4,
                                 enableTenant: false,
                                 isExternal: false,
                                 countOfUser: 17,
                                 countOfUserCascaded: 17,
                                 sort: null,
                                 remark: null,
                                 sourceId: null,
                                 id: '165106603304026112',
                              },
                              {
                                 parentOrganizationName: '技术',
                                 organizationTypeName: '部门',
                                 leadersName: null,
                                 location: null,
                                 children: [
                                    {
                                       parentOrganizationName: '智能制造中心',
                                       organizationTypeName: '车间',
                                       leadersName: null,
                                       location: null,
                                       children: [],
                                       positions: null,
                                       externalRelations: null,
                                       parentId: '165121379526639616',
                                       name: '产品设计',
                                       code: null,
                                       type: 5,
                                       enableTenant: false,
                                       isExternal: false,
                                       countOfUser: 7,
                                       countOfUserCascaded: 7,
                                       sort: 2,
                                       remark: null,
                                       sourceId: null,
                                       id: '167957294401847296',
                                    },
                                    {
                                       parentOrganizationName: '智能制造中心',
                                       organizationTypeName: '车间',
                                       leadersName: null,
                                       location: null,
                                       children: [],
                                       positions: null,
                                       externalRelations: null,
                                       parentId: '165121379526639616',
                                       name: '项目工程',
                                       code: null,
                                       type: 5,
                                       enableTenant: false,
                                       isExternal: false,
                                       countOfUser: 2,
                                       countOfUserCascaded: 2,
                                       sort: 2.5,
                                       remark: null,
                                       sourceId: null,
                                       id: '195555519266684928',
                                    },
                                    {
                                       parentOrganizationName: '智能制造中心',
                                       organizationTypeName: '车间',
                                       leadersName: null,
                                       location: null,
                                       children: [],
                                       positions: null,
                                       externalRelations: null,
                                       parentId: '165121379526639616',
                                       name: '平面设计部',
                                       code: null,
                                       type: 5,
                                       enableTenant: false,
                                       isExternal: false,
                                       countOfUser: 1,
                                       countOfUserCascaded: 1,
                                       sort: 3,
                                       remark: null,
                                       sourceId: null,
                                       id: '239034643708510208',
                                    },
                                 ],
                                 positions: null,
                                 externalRelations: null,
                                 parentId: '164306583474536448',
                                 name: '智能制造中心',
                                 code: null,
                                 type: 4,
                                 enableTenant: false,
                                 isExternal: false,
                                 countOfUser: 1,
                                 countOfUserCascaded: 11,
                                 sort: null,
                                 remark: null,
                                 sourceId: null,
                                 id: '165121379526639616',
                              },
                              {
                                 parentOrganizationName: '技术',
                                 organizationTypeName: '部门',
                                 leadersName: null,
                                 location: null,
                                 children: [],
                                 positions: null,
                                 externalRelations: null,
                                 parentId: '164306583474536448',
                                 name: '研发中心3',
                                 code: 'devcenter',
                                 type: 4,
                                 enableTenant: false,
                                 isExternal: false,
                                 countOfUser: 1,
                                 countOfUserCascaded: 1,
                                 sort: null,
                                 remark: null,
                                 sourceId: null,
                                 id: '197420665094144000',
                              },
                              {
                                 parentOrganizationName: '技术',
                                 organizationTypeName: '部门',
                                 leadersName: null,
                                 location: null,
                                 children: [
                                    {
                                       parentOrganizationName: '测试中心',
                                       organizationTypeName: '车间',
                                       leadersName: null,
                                       location: null,
                                       children: [],
                                       positions: null,
                                       externalRelations: null,
                                       parentId: '217637710905606144',
                                       name: '测试A组',
                                       code: null,
                                       type: 5,
                                       enableTenant: false,
                                       isExternal: false,
                                       countOfUser: 1,
                                       countOfUserCascaded: 1,
                                       sort: null,
                                       remark: null,
                                       sourceId: null,
                                       id: '217684943243968512',
                                    },
                                    {
                                       parentOrganizationName: '测试中心',
                                       organizationTypeName: '车间',
                                       leadersName: null,
                                       location: null,
                                       children: [],
                                       positions: null,
                                       externalRelations: null,
                                       parentId: '217637710905606144',
                                       name: '测试B组',
                                       code: null,
                                       type: 5,
                                       enableTenant: false,
                                       isExternal: false,
                                       countOfUser: 1,
                                       countOfUserCascaded: 1,
                                       sort: null,
                                       remark: null,
                                       sourceId: null,
                                       id: '268331587140190208',
                                    },
                                 ],
                                 positions: null,
                                 externalRelations: null,
                                 parentId: '164306583474536448',
                                 name: '测试中心',
                                 code: null,
                                 type: 4,
                                 enableTenant: false,
                                 isExternal: false,
                                 countOfUser: 4,
                                 countOfUserCascaded: 6,
                                 sort: null,
                                 remark: null,
                                 sourceId: null,
                                 id: '217637710905606144',
                              },
                           ],
                           positions: null,
                           externalRelations: null,
                           parentId: '167954423925047296',
                           name: '技术',
                           code: 'JS',
                           type: 3,
                           enableTenant: false,
                           isExternal: false,
                           countOfUser: 12,
                           countOfUserCascaded: 47,
                           sort: 2,
                           remark: null,
                           sourceId: null,
                           id: '164306583474536448',
                        },
                     ],
                     positions: null,
                     externalRelations: null,
                     parentId: '164306494895030272',
                     name: '中智达',
                     code: '',
                     type: 2,
                     enableTenant: false,
                     isExternal: false,
                     countOfUser: 1,
                     countOfUserCascaded: 49,
                     sort: null,
                     remark: null,
                     sourceId: null,
                     id: '167954423925047296',
                  },
                  {
                     parentOrganizationName: '浙江中智达科技有限公司',
                     organizationTypeName: '公司',
                     leadersName: null,
                     location: null,
                     children: [],
                     positions: null,
                     externalRelations: null,
                     parentId: '164306494895030272',
                     name: '石油分公司',
                     code: null,
                     type: 2,
                     enableTenant: false,
                     isExternal: false,
                     countOfUser: 2,
                     countOfUserCascaded: 7,
                     sort: null,
                     remark: null,
                     sourceId: null,
                     id: '264385199603843072',
                  },
                  {
                     parentOrganizationName: '浙江中智达科技有限公司',
                     organizationTypeName: '工厂',
                     leadersName: null,
                     location: null,
                     children: [
                        {
                           parentOrganizationName: '石油第一分厂',
                           organizationTypeName: '部门',
                           leadersName: null,
                           location: null,
                           children: [],
                           positions: null,
                           externalRelations: null,
                           parentId: '264385301546401792',
                           name: '安全部',
                           code: null,
                           type: 4,
                           enableTenant: false,
                           isExternal: false,
                           countOfUser: 0,
                           countOfUserCascaded: 0,
                           sort: null,
                           remark: null,
                           sourceId: null,
                           id: '264385480106311680',
                        },
                        {
                           parentOrganizationName: '石油第一分厂',
                           organizationTypeName: '部门',
                           leadersName: null,
                           location: null,
                           children: [],
                           positions: null,
                           externalRelations: null,
                           parentId: '264385301546401792',
                           name: '总经办',
                           code: null,
                           type: 4,
                           enableTenant: false,
                           isExternal: false,
                           countOfUser: 0,
                           countOfUserCascaded: 0,
                           sort: null,
                           remark: null,
                           sourceId: null,
                           id: '264385577862955008',
                        },
                        {
                           parentOrganizationName: '石油第一分厂',
                           organizationTypeName: '部门',
                           leadersName: null,
                           location: null,
                           children: [],
                           positions: null,
                           externalRelations: null,
                           parentId: '264385301546401792',
                           name: '生产部',
                           code: null,
                           type: 4,
                           enableTenant: false,
                           isExternal: false,
                           countOfUser: 1,
                           countOfUserCascaded: 1,
                           sort: 3,
                           remark: null,
                           sourceId: null,
                           id: '264385418294853632',
                        },
                     ],
                     positions: null,
                     externalRelations: null,
                     parentId: '164306494895030272',
                     name: '石油第一分厂',
                     code: null,
                     type: 3,
                     enableTenant: false,
                     isExternal: false,
                     countOfUser: 2,
                     countOfUserCascaded: 3,
                     sort: null,
                     remark: null,
                     sourceId: null,
                     id: '264385301546401792',
                  },
                  {
                     parentOrganizationName: '浙江中智达科技有限公司',
                     organizationTypeName: '部门',
                     leadersName: null,
                     location: null,
                     children: [],
                     positions: null,
                     externalRelations: null,
                     parentId: '164306494895030272',
                     name: '证书测试',
                     code: null,
                     type: 4,
                     enableTenant: false,
                     isExternal: false,
                     countOfUser: 2,
                     countOfUserCascaded: 2,
                     sort: null,
                     remark: null,
                     sourceId: null,
                     id: '382573632645365760',
                  },
               ],
               positions: null,
               externalRelations: null,
               parentId: null,
               name: '浙江中智达科技有限公司',
               code: '',
               type: 1,
               enableTenant: false,
               isExternal: false,
               countOfUser: 8,
               countOfUserCascaded: 66,
               sort: null,
               remark: null,
               sourceId: null,
               id: '164306494895030272',
            },
            {
               parentOrganizationName: null,
               organizationTypeName: '工厂',
               leadersName: null,
               location: null,
               children: [
                  {
                     parentOrganizationName: '石油第二分厂',
                     organizationTypeName: '部门',
                     leadersName: null,
                     location: null,
                     children: [
                        {
                           parentOrganizationName: '设备部',
                           organizationTypeName: '部门',
                           leadersName: null,
                           location: null,
                           children: [],
                           positions: null,
                           externalRelations: null,
                           parentId: '264385367409557504',
                           name: '第一车间',
                           code: null,
                           type: 4,
                           enableTenant: false,
                           isExternal: false,
                           countOfUser: 1,
                           countOfUserCascaded: 1,
                           sort: null,
                           remark: null,
                           sourceId: null,
                           id: '264385652836139008',
                        },
                        {
                           parentOrganizationName: '设备部',
                           organizationTypeName: '车间',
                           leadersName: '金紫依',
                           location: null,
                           children: [],
                           positions: null,
                           externalRelations: null,
                           parentId: '264385367409557504',
                           name: '第二车间',
                           code: null,
                           type: 5,
                           enableTenant: false,
                           isExternal: false,
                           countOfUser: 2,
                           countOfUserCascaded: 2,
                           sort: null,
                           remark: null,
                           sourceId: null,
                           id: '264385766090735616',
                        },
                     ],
                     positions: null,
                     externalRelations: null,
                     parentId: '264388303879536640',
                     name: '设备部',
                     code: null,
                     type: 4,
                     enableTenant: false,
                     isExternal: false,
                     countOfUser: 2,
                     countOfUserCascaded: 5,
                     sort: null,
                     remark: null,
                     sourceId: null,
                     id: '264385367409557504',
                  },
               ],
               positions: null,
               externalRelations: null,
               parentId: null,
               name: '石油第二分厂',
               code: null,
               type: 3,
               enableTenant: true,
               isExternal: false,
               countOfUser: 15,
               countOfUserCascaded: 13,
               sort: null,
               remark: null,
               sourceId: null,
               id: '264388303879536640',
            },
            {
               parentOrganizationName: null,
               organizationTypeName: '集团',
               leadersName: null,
               location: null,
               children: [],
               positions: null,
               externalRelations: null,
               parentId: null,
               name: '测试第二集团',
               code: null,
               type: 1,
               enableTenant: false,
               isExternal: false,
               countOfUser: 0,
               countOfUserCascaded: 0,
               sort: null,
               remark: null,
               sourceId: null,
               id: '344838785814626304',
            },
            {
               parentOrganizationName: null,
               organizationTypeName: '集团',
               leadersName: null,
               location: null,
               children: [
                  {
                     parentOrganizationName: '测试0921',
                     organizationTypeName: '公司',
                     leadersName: null,
                     location: null,
                     children: [
                        {
                           parentOrganizationName: '测试0921-1',
                           organizationTypeName: '部门',
                           leadersName: '测试1027,测试10262,测试10263',
                           location: null,
                           children: [
                              {
                                 parentOrganizationName: '测试0921-1-1',
                                 organizationTypeName: '车间',
                                 leadersName: '余华伟',
                                 location: null,
                                 children: [
                                    {
                                       parentOrganizationName: '测试11141',
                                       organizationTypeName: '车间',
                                       leadersName: '测试小b',
                                       location: null,
                                       children: [
                                          {
                                             parentOrganizationName: '测试11142',
                                             organizationTypeName: '车间',
                                             leadersName: null,
                                             location: null,
                                             children: [
                                                {
                                                   parentOrganizationName: '测试11143',
                                                   organizationTypeName: '车间',
                                                   leadersName: '金紫依',
                                                   location: null,
                                                   children: [],
                                                   positions: null,
                                                   externalRelations: null,
                                                   parentId: '380051677966893056',
                                                   name: '测试11144',
                                                   code: null,
                                                   type: 5,
                                                   enableTenant: false,
                                                   isExternal: false,
                                                   countOfUser: 1,
                                                   countOfUserCascaded: 1,
                                                   sort: null,
                                                   remark: null,
                                                   sourceId: null,
                                                   id: '380051752294154240',
                                                },
                                             ],
                                             positions: null,
                                             externalRelations: null,
                                             parentId: '380051493866307584',
                                             name: '测试11143',
                                             code: null,
                                             type: 5,
                                             enableTenant: false,
                                             isExternal: false,
                                             countOfUser: 0,
                                             countOfUserCascaded: 1,
                                             sort: null,
                                             remark: null,
                                             sourceId: null,
                                             id: '380051677966893056',
                                          },
                                       ],
                                       positions: null,
                                       externalRelations: null,
                                       parentId: '380051388064989184',
                                       name: '测试11142',
                                       code: null,
                                       type: 5,
                                       enableTenant: false,
                                       isExternal: false,
                                       countOfUser: 0,
                                       countOfUserCascaded: 1,
                                       sort: null,
                                       remark: null,
                                       sourceId: null,
                                       id: '380051493866307584',
                                    },
                                 ],
                                 positions: null,
                                 externalRelations: null,
                                 parentId: '360459333705793536',
                                 name: '测试11141',
                                 code: null,
                                 type: 5,
                                 enableTenant: false,
                                 isExternal: false,
                                 countOfUser: 0,
                                 countOfUserCascaded: 1,
                                 sort: null,
                                 remark: null,
                                 sourceId: null,
                                 id: '380051388064989184',
                              },
                           ],
                           positions: null,
                           externalRelations: null,
                           parentId: '360459204017913856',
                           name: '测试0921-1-1',
                           code: null,
                           type: 4,
                           enableTenant: false,
                           isExternal: false,
                           countOfUser: 0,
                           countOfUserCascaded: 1,
                           sort: null,
                           remark: null,
                           sourceId: null,
                           id: '360459333705793536',
                        },
                        {
                           parentOrganizationName: '测试0921-1',
                           organizationTypeName: '部门',
                           leadersName: '罗宗民,陈海豪',
                           location: null,
                           children: [],
                           positions: null,
                           externalRelations: null,
                           parentId: '360459204017913856',
                           name: '测试0921-1-2',
                           code: null,
                           type: 4,
                           enableTenant: false,
                           isExternal: false,
                           countOfUser: 0,
                           countOfUserCascaded: 0,
                           sort: null,
                           remark: null,
                           sourceId: null,
                           id: '360459374977744896',
                        },
                     ],
                     positions: null,
                     externalRelations: null,
                     parentId: '360459125517320192',
                     name: '测试0921-1',
                     code: null,
                     type: 2,
                     enableTenant: false,
                     isExternal: false,
                     countOfUser: 4,
                     countOfUserCascaded: 5,
                     sort: null,
                     remark: null,
                     sourceId: null,
                     id: '360459204017913856',
                  },
                  {
                     parentOrganizationName: '测试0921',
                     organizationTypeName: '公司',
                     leadersName: '测试10264',
                     location: null,
                     children: [
                        {
                           parentOrganizationName: '测试0921-2',
                           organizationTypeName: '部门',
                           leadersName: '测试1027,测试10262,测试10263',
                           location: null,
                           children: [
                              {
                                 parentOrganizationName: '测试0921-2-1',
                                 organizationTypeName: '工厂',
                                 leadersName: null,
                                 location: null,
                                 children: [],
                                 positions: null,
                                 externalRelations: null,
                                 parentId: '360459490774089728',
                                 name: '测试0921-2-1-1',
                                 code: null,
                                 type: 3,
                                 enableTenant: false,
                                 isExternal: false,
                                 countOfUser: 0,
                                 countOfUserCascaded: 0,
                                 sort: null,
                                 remark: null,
                                 sourceId: null,
                                 id: '392726371085975552',
                              },
                           ],
                           positions: null,
                           externalRelations: null,
                           parentId: '360459255867899904',
                           name: '测试0921-2-1',
                           code: null,
                           type: 4,
                           enableTenant: false,
                           isExternal: false,
                           countOfUser: 0,
                           countOfUserCascaded: 0,
                           sort: null,
                           remark: null,
                           sourceId: null,
                           id: '360459490774089728',
                        },
                        {
                           parentOrganizationName: '测试0921-2',
                           organizationTypeName: '部门',
                           leadersName: '王璐,陈海豪,关旭鹏',
                           location: null,
                           children: [],
                           positions: null,
                           externalRelations: null,
                           parentId: '360459255867899904',
                           name: '测试0921-2-2',
                           code: null,
                           type: 4,
                           enableTenant: false,
                           isExternal: false,
                           countOfUser: 0,
                           countOfUserCascaded: 0,
                           sort: null,
                           remark: null,
                           sourceId: null,
                           id: '360459546373783552',
                        },
                     ],
                     positions: null,
                     externalRelations: null,
                     parentId: '360459125517320192',
                     name: '测试0921-2',
                     code: null,
                     type: 2,
                     enableTenant: true,
                     isExternal: false,
                     countOfUser: 1,
                     countOfUserCascaded: 1,
                     sort: null,
                     remark: null,
                     sourceId: null,
                     id: '360459255867899904',
                  },
               ],
               positions: null,
               externalRelations: null,
               parentId: null,
               name: '测试0921',
               code: null,
               type: 1,
               enableTenant: false,
               isExternal: false,
               countOfUser: 4,
               countOfUserCascaded: 10,
               sort: null,
               remark: null,
               sourceId: null,
               id: '360459125517320192',
            },
            {
               parentOrganizationName: null,
               organizationTypeName: '集团',
               leadersName: '浙化集团老板',
               location: null,
               children: [
                  {
                     parentOrganizationName: '浙化集团（勿删）',
                     organizationTypeName: '公司',
                     leadersName: '湖州化工股份有限公司老板',
                     location: null,
                     children: [
                        {
                           parentOrganizationName: '湖州化工股份有限公司（勿删）',
                           organizationTypeName: '工厂',
                           leadersName: '西厂老板',
                           location: null,
                           children: [
                              {
                                 parentOrganizationName: '西厂',
                                 organizationTypeName: '部门',
                                 leadersName: null,
                                 location: null,
                                 children: [],
                                 positions: null,
                                 externalRelations: null,
                                 parentId: '388365018170785792',
                                 name: '财务部',
                                 code: null,
                                 type: 4,
                                 enableTenant: false,
                                 isExternal: false,
                                 countOfUser: 0,
                                 countOfUserCascaded: 0,
                                 sort: null,
                                 remark: null,
                                 sourceId: null,
                                 id: '388365131228250112',
                              },
                              {
                                 parentOrganizationName: '西厂',
                                 organizationTypeName: '部门',
                                 leadersName: '硅胶部老板',
                                 location: null,
                                 children: [
                                    {
                                       parentOrganizationName: '硅胶部',
                                       organizationTypeName: '车间',
                                       leadersName: '硅胶成品车间老板',
                                       location: null,
                                       children: [],
                                       positions: null,
                                       externalRelations: null,
                                       parentId: '388365288577564672',
                                       name: '硅胶成品车间',
                                       code: null,
                                       type: 5,
                                       enableTenant: false,
                                       isExternal: false,
                                       countOfUser: 1,
                                       countOfUserCascaded: 1,
                                       sort: null,
                                       remark: null,
                                       sourceId: null,
                                       id: '388365442755985408',
                                    },
                                 ],
                                 positions: null,
                                 externalRelations: null,
                                 parentId: '388365018170785792',
                                 name: '硅胶部',
                                 code: null,
                                 type: 4,
                                 enableTenant: false,
                                 isExternal: false,
                                 countOfUser: 1,
                                 countOfUserCascaded: 2,
                                 sort: null,
                                 remark: null,
                                 sourceId: null,
                                 id: '388365288577564672',
                              },
                           ],
                           positions: null,
                           externalRelations: null,
                           parentId: '388364721176313856',
                           name: '西厂',
                           code: null,
                           type: 3,
                           enableTenant: false,
                           isExternal: false,
                           countOfUser: 1,
                           countOfUserCascaded: 3,
                           sort: null,
                           remark: null,
                           sourceId: null,
                           id: '388365018170785792',
                        },
                        {
                           parentOrganizationName: '湖州化工股份有限公司（勿删）',
                           organizationTypeName: '工厂',
                           leadersName: null,
                           location: null,
                           children: [],
                           positions: null,
                           externalRelations: null,
                           parentId: '388364721176313856',
                           name: '东厂',
                           code: null,
                           type: 3,
                           enableTenant: false,
                           isExternal: false,
                           countOfUser: 0,
                           countOfUserCascaded: 0,
                           sort: null,
                           remark: null,
                           sourceId: null,
                           id: '388365080544280576',
                        },
                     ],
                     positions: null,
                     externalRelations: null,
                     parentId: '388364382276550656',
                     name: '湖州化工股份有限公司（勿删）',
                     code: null,
                     type: 2,
                     enableTenant: true,
                     isExternal: false,
                     countOfUser: 1,
                     countOfUserCascaded: 4,
                     sort: null,
                     remark: null,
                     sourceId: null,
                     id: '388364721176313856',
                  },
                  {
                     parentOrganizationName: '浙化集团（勿删）',
                     organizationTypeName: '公司',
                     leadersName: null,
                     location: null,
                     children: [],
                     positions: null,
                     externalRelations: null,
                     parentId: '388364382276550656',
                     name: '台州化工股份有限公司（勿删）',
                     code: null,
                     type: 2,
                     enableTenant: true,
                     isExternal: false,
                     countOfUser: 0,
                     countOfUserCascaded: 0,
                     sort: null,
                     remark: null,
                     sourceId: null,
                     id: '388364770618769408',
                  },
               ],
               positions: null,
               externalRelations: null,
               parentId: null,
               name: '浙化集团（勿删）',
               code: null,
               type: 1,
               enableTenant: false,
               isExternal: false,
               countOfUser: 2,
               countOfUserCascaded: 6,
               sort: null,
               remark: null,
               sourceId: null,
               id: '388364382276550656',
            },
            {
               parentOrganizationName: null,
               organizationTypeName: '集团',
               leadersName: null,
               location: null,
               children: [],
               positions: null,
               externalRelations: null,
               parentId: null,
               name: 'TestExternal1216',
               code: null,
               type: 1,
               enableTenant: false,
               isExternal: true,
               countOfUser: 0,
               countOfUserCascaded: 1,
               sort: null,
               remark: null,
               sourceId: null,
               id: '391631493761466368',
            },
            {
               parentOrganizationName: null,
               organizationTypeName: '公司',
               leadersName: null,
               location: null,
               children: [],
               positions: null,
               externalRelations: null,
               parentId: null,
               name: 'TestExternal1219',
               code: null,
               type: 2,
               enableTenant: false,
               isExternal: true,
               countOfUser: 2,
               countOfUserCascaded: 2,
               sort: null,
               remark: null,
               sourceId: null,
               id: 'e20221219',
            },
            {
               parentOrganizationName: null,
               organizationTypeName: '公司',
               leadersName: null,
               location: null,
               children: [],
               positions: null,
               externalRelations: null,
               parentId: null,
               name: 'byb021',
               code: null,
               type: 2,
               enableTenant: false,
               isExternal: true,
               countOfUser: 1,
               countOfUserCascaded: 1,
               sort: 20221221,
               remark: null,
               sourceId: null,
               id: '1602844445525442560',
            },
            {
               parentOrganizationName: null,
               organizationTypeName: '公司',
               leadersName: null,
               location: null,
               children: [],
               positions: null,
               externalRelations: null,
               parentId: null,
               name: '12-29 测试',
               code: null,
               type: 2,
               enableTenant: false,
               isExternal: true,
               countOfUser: 1,
               countOfUserCascaded: 1,
               sort: 20221229,
               remark: null,
               sourceId: null,
               id: '1608271612598059008',
            },
            {
               parentOrganizationName: null,
               organizationTypeName: '公司',
               leadersName: null,
               location: null,
               children: [],
               positions: null,
               externalRelations: null,
               parentId: null,
               name: '11-29 状态测试',
               code: null,
               type: 2,
               enableTenant: false,
               isExternal: true,
               countOfUser: 0,
               countOfUserCascaded: 0,
               sort: 20230103,
               remark: null,
               sourceId: null,
               id: '1599981493096882176',
            },
         ],
         replaceFields: {
            children: 'children',
            title: 'name',
            key: 'name',
            value: 'id',
         },
         eq: [],
      }
   },
}
</script>

<style scoped></style>
